/*
-- Query: select * from poker_user where id > 13580
LIMIT 0, 1000

-- Date: 2019-02-10 20:20
*/
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13581,'joe','schmoe','jsch','ab','abc@def.com',0,'2018-12-22','2018-12-22',100,NULL,NULL,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13582,'tew','new','tns','tns','todd@toddandpatti.com',0,'2019-01-10',NULL,NULL,'2019-01-10',100,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13583,'test1','','test1','test1','todd@toddandpatti.com',0,'2019-01-10',NULL,NULL,'2019-01-10',100,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13584,'test2','','test2','test2','todd@toddandpatti.com',0,'2019-01-10','2019-01-10',100,NULL,NULL,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13585,'Jim','Ryan','jimryan63','jumanji1','jim.ryan.63@gmail.com',0,'2019-01-12','2019-01-12',100,NULL,NULL,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13586,'George','Lang','glang23','myCCP23@','Glang23@gmail.com',0,'2019-01-12','2019-01-12',100,NULL,NULL,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13587,'Paul','Kula','pkula','2014BlackMustang','paul.kula@sbcglobal.net',0,'2019-01-12','2019-01-12',100,NULL,NULL,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13588,'Paul','sandhu','poker.paul','ccp.123','paul_bills2pay@yahoo.com',0,'2019-01-25','2019-01-26',100,NULL,NULL,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13589,'marc','castro','Catsrom76','Nacho1976','mcastro5662@yahoo.com',0,'2019-01-26','2019-01-26',100,NULL,NULL,1);
INSERT INTO `poker_user` (`id`,`first_name`,`last_name`,`username`,`password`,`email`,`administrator`,`registration_date`,`approval_date`,`approval_userid`,`rejection_date`,`rejection_userid`,`active`) VALUES (13590,'Bill','Wertz','irish_wertzy','jartgo1234','billwertz@sbcglobal.net',0,'2019-01-26','2019-01-26',100,NULL,NULL,1);
